### PR TITLE
typo in CSS property

### PR DESCRIPTION
**Pull request by TweetPressFr**
"bolder" ~~does not exist~~, this PR replaces it with "bold"

### CODE REVIEW

**Comment by raphaelgoetter** [comment]
Actually, `font-weigh: bolder` exist (https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight).

But you're right: it's not the appropriate value here.

**Comment by TweetPressFr** [comment]
ok I see, it's for children elements.
Good to know ^^

**Comment by TweetPressFr** [comment]
Do you plan to merge this @raphaelgoetter ? so I can delete my fork after.

**Comment by TweetPressFr** [comment]
thanks for this great css base btw, see ya later :)

**Pull request merged**
